[package]
name = "backend-tools"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/lhwdev/notebook"

[dependencies]
toml = "0.4.2"
liquid = "^0.26.0"
serde = "^1.0.144"
serde_json = "^1"
notify = "^4.0.0"
